// Canonical list of supported Pakistani cities.
// Display labels are Title Case; the value submitted to the API is the
// lowercase form, which matches the backend's ticket-routing convention
// (sub-admin city, order shippingAddress.city and ticket.city are all lowercase).
export const PAKISTAN_CITIES = [
  'Abbottabad',
  'Bahawalpur',
  'Bahawalnagar',
  'Burewala',
  'Charsadda',
  'Chiniot',
  'Dadu',
  'Dera Ghazi Khan',
  'Faisalabad',
  'Gilgit',
  'Gojra',
  'Gujranwala',
  'Gujrat',
  'Hafizabad',
  'Hyderabad',
  'Islamabad',
  'Jacobabad',
  'Jhang',
  'Jhelum',
  'Kamoke',
  'Karachi',
  'Kasur',
  'Khanewal',
  'Khanpur',
  'Kohat',
  'Lahore',
  'Larkana',
  'Mandi Bahauddin',
  'Mardan',
  'Mingora',
  'Mirpur Khas',
  'Multan',
  'Muridke',
  'Muzaffargarh',
  'Muzaffarabad',
  'Nawabshah',
  'Okara',
  'Peshawar',
  'Quetta',
  'Rahim Yar Khan',
  'Rawalpindi',
  'Sadiqabad',
  'Sahiwal',
  'Sargodha',
  'Sheikhupura',
  'Sialkot',
  'Sukkur',
  'Turbat',
  'Wah Cantonment',
]

export default PAKISTAN_CITIES
